#!/bin/bash

set -e -u -o pipefail

INSTALL_DIR="$HOME/Library/Application Support/iTerm2/DynamicProfiles"
SOURCE_DIR="$(dirname "$0")/profiles"

REPO="$(git rev-parse --show-toplevel)"
YAML2JSON="${REPO}/bin/yaml2json"


# Converts YAML profile to JSON and installs.
# $1: profile YAML in the $SOURCE_DIR.
install_profile () {
    profile_yaml="$1"
    profile_json="${INSTALL_DIR}/$(basename "$profile_yaml" .yaml).json"
    "$YAML2JSON" < "${profile_yaml}" > "${profile_json}"
}


# Main
find "${SOURCE_DIR}" -type f -name '*.yaml' -print \
| while read -r profile_yaml; do
    install_profile "$profile_yaml"
done
