#!/bin/sh

set -e -u -o pipefail


NAME="$(basename -- "$0")"
PREFIX="$(dirname -- "$0")"

USAGE="USAGE: $NAME [-h|--help]"
HELP="$USAGE
    Installs prerequisites, utilities, dotfiles, apps and settings."

# Parse arguments.
while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            echo "$HELP"
            exit 0
            ;;
        *)
            echo "Invalid argument $1." 1>&2
            echo "$USAGE" 1>&2
            exit 1
    esac
done


echo "Installing software prerequisites." 1>&2
"$PREFIX/installers/prereq"

echo "Installing utilities and apps." 1>&2
ostype="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$ostype" in
    linux*)
        brewfile="$PREFIX/installers/Brewfile.linuxbrew"
        brew_path="$HOME/.linuxbrew/bin"
        ;;
    darwin*)
        brewfile="$PREFIX/installers/Brewfile.homebrew"
        brew_path="/usr/local/bin"
        ;;
    *)
        echo "Unknown OS." 1>&2
        exit 1
        ;;
esac
"$PREFIX/installers/brew" --brewfile "$brewfile"
export PATH="${brew_path}:$PATH"

if which pip3 >/dev/null 2>&1; then
    echo "Installing python packages." 1>&2
    pip3 install -q -r "$PREFIX/installers/pip3_requirements.txt"
fi

echo "Installing dotfiles." 1>&2
"$PREFIX/installers/dotfiles" --freshrc "$PREFIX/installers/freshrc" --update
