#!/bin/bash

UrlFile=.vim/bundle/vim-extensions.url
LogFile=$(mktemp /tmp/`basename $0`.XXXXXXXX)

if [[ ! -f $UrlFile ]]; then
  echo "Usage error: URL file not found; run from top level of repo"
  exit 1
fi

regex_comment='^#'
cat $UrlFile | while read extension url branch; do
  if [[ -z $extension || $extension =~ $regex_comment ]]; then
    continue
  fi
  prefix=.vim/bundle/$extension
  if [[ $(find $prefix -mindepth 1 | wc -l) -gt 0 ]]; then
    echo "SKIP $extension: $prefix not empty" >> $LogFile
    continue
  fi
  if [[ -d $prefix ]]; then
    rmdir $prefix
  fi
  if [[ -z $branch ]]; then
    branch=master
  fi
  echo "INSTALL $extension using 'git subtree' and commit to repo" | tee -a $LogFile
  echo git subtree add --squash -P $prefix $url $branch >> $LogFile
  git subtree add --squash -P $prefix $url $branch >> $LogFile
done
echo "LOG to $LogFile"
