#!/bin/sh

set -e -u -o pipefail


# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
defaults write com.apple.AppleMultitouchTrackpad Dragging -bool false

# Enable full keyboard access for all controls
# (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 2

# Use scroll gesture with the Ctrl (^) modifier key to zoom
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
# Follow the keyboard focus while zoomed in
defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

# Set language and text formats
defaults write NSGlobalDomain AppleLanguages -array 'en'
defaults write NSGlobalDomain AppleLocale -string 'en_US'

defaults write com.apple.HIToolbox AppleCurrentKeyboardLayoutInputSourceID -string "com.apple.keylayout.UnicodeHexInput";

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Disable smart dashes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Disable automatic period substitution as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Use Fn modifier to invoke function keys.
defaults write NSGlobalDomain com.apple.keyboard.fnState -bool false;

# Key remapping: CapsLock -> Control.
kb_properties="$(ioreg -c IOHIDKeyboard -r -d1)"
kb_count="$(echo "$kb_properties" | grep -c ProductID)"
kb_vendor_id="$(echo "$kb_properties" | sed -n -e 's/^ *"VendorID" *= *//p')"
kb_product_id="$(echo "$kb_properties" | sed -n -e 's/^ *"ProductID" *= *//p')"
if [ "$kb_count" -eq 1 ] && [ ! -z "$kb_vendor_id" ] && [ ! -z "$kb_product_id" ]; then
    defaults -currentHost write NSGlobalDomain \
        "com.apple.keyboard.modifiermapping.${kb_vendor_id}-${kb_product_id}-0" -array \
        "<dict> \
            <key>HIDKeyboardModifierMappingSrc</key> \
            <integer>0</integer> \
            <key>HIDKeyboardModifierMappingDst</key> \
            <integer>2</integer> \
        </dict>"
else
    echo "WARNING: Key remapping skipped. Unable to determine keyboard vendor and product IDs." 1>&2
fi
# Key codes (ref: http://apple.stackexchange.com/a/88096).
#     -1    None
#      0    Caps Lock
#      1    Shift (Left)
#      2    Control (Left)
#      3    Option (Left)
#      4    Command (Left)
#      5    Keypad 0
#      6    Help
#      9    Shift (Right)
#     10    Control (Right)
#     11    Option (Right)
#     12    Command (Right)
