#!/bin/bash

set -e -u -o pipefail

if ! which pip3 >/dev/null 2>&1; then
    echo "pip3 not found. Please check that python3 is installed and in $PATH" 1>&2
fi

if [[ -n "$VIRTUAL_ENV" ]]; then
    echo "Cannot run with an active python virtual env. Please run 'deactivate'." 1>&2
fi

pip3 install -q -r "$PREFIX/installers/pip3_requirements.txt"
