#!/bin/bash

set -e -u -o pipefail

NAME="$(basename -- "$0")"
REQS_FILE="$(dirname -- "$0")/pip3_requirements.txt"

USAGE="USAGE: $NAME [-h|--help] [-v|--verbose]"
HELP="
SYNOPSIS

Installs Python packages listed in $REQS_FILE
into the system Python library path using pip3. It will not install packages in
a virtual environment.

$USAGE
"

# Parse arguments.
verbose="false"
while [ $# -gt 0 ]; do
    case "$1" in
        -v|--verbose)
            verbose="true"
            shift
            ;;
        -h|--help)
            echo "$HELP"
            exit 0
            ;;
        *)
            echo "$USAGE" 1>&2
            exit 1
            ;;
    esac
done

if ! which pip3 >/dev/null 2>&1; then
    echo "pip3 not found. Check that python3 is installed and in $PATH" 1>&2
    exit 1
fi

if [[ -n "${VIRTUAL_ENV:-}" ]]; then
    echo "Cannot run with an active virtualenv. Please run 'deactivate'." 1>&2
    exit 1
fi

cmd=("pip3" "install" "-r" "$REQS_FILE")
if [[ "$verbose" == "true" ]]; then
    echo "Running ${cmd[*]}" 1>&2
    "${cmd[@]}"
else
    "${cmd[@]}" -q
fi
