#!/bin/sh

set -e -u -o pipefail


NAME="$(basename -- "$0")"
PREFIX="$(dirname -- "$0")"
OSTYPE="$(uname -s | tr '[:upper:]' '[:lower:]')"
PREFS_JS="$PREFIX/prefs.js"


# Show usage.
usage () {
    echo "Usage: $NAME [-h|--help]"
    echo '    Merges $PREFS_JS with firefox config.'
}


# ----------  Logging  -------------------------------------------------------

# Initialize logging by setting global variables.
# Args: None.
init_logger () {
    if [ -t 1 ]; then
        NORMAL="\e[0m"
        BOLD="\e[1m"
        RED="\e[31m"
        YELLOW="\e[33m"
    else
        NORMAL=""
        BOLD=""
        RED=""
        YELLOW=""
    fi
}

# Output formatted error message _and exit_.
# Args:
#   $@: Messages.
error () {
    env echo -e "${RED}ERROR${NORMAL}${BOLD}   [$NAME]  $*${NORMAL}"
    exit 1
}

# Output formatted warning messages.
# Args:
#   $@: Messages.
warn () {
    env echo -e "${YELLOW}WARNING${NORMAL}${BOLD} [$NAME]  $*${NORMAL}"
}

# Output formatted informational messages.
# Args:
#   $@: Messages.
info () {
    env echo -e "${BOLD}INFO    [$NAME]  $*${NORMAL}"
}

# Run a command, logging its output. If an error is encountered, output an error message and exit.
# Args:
#   $@: Command and arguments to be run.
run () {
    info "Running: $* (in $(pwd))."
    ("$@" 2>&1 | while IFS='' read -r line; do echo "        $line"; done) \
        || error " command failed."
}


# ----------  main  ----------------------------------------------------------

# Check usage.
if [ $# -eq 1 ] && ([ "$1" = "-h" ] || [ "$1" = "--help" ]); then
    usage
    exit 0
fi
if [ $# -gt 0 ]; then
    usage
    exit 1
fi

# OS-specific prereqs.
case "$OSTYPE" in
    linux*)
        # Exit if firefox is running.
        # Calculate path to prefs.js.
        # Merge prefs.
        info "Merging."
        run sudo apt-get install build-essential curl file git python-setuptools ruby
        ;;
    darwin*)
        info "Satisfying MacOS-specific prerequisites."
        test -x /usr/bin/clang || run xcode-select --install
        ;;
    *)
        error "Unsupported OS: $OSTYPE"
        ;;
esac

# Generic prereqs.
info "Satisfying non-OS-specific prerequisites."
which ruby >/dev/null 2>&1 || error "Missing dependency - ruby not found."

cat firefox/prefs.js | grep '^[^#/]' | cat - <(cat ~/Library/Application\
    Support/Firefox/Profiles/l096ebgw.default/prefs.js | grep '^[^#/ ]') | sort -t, -k1,1 -s -u >
merged.js

# sed -i -e "s#DOWNLOAD_DIR#${HOME}/Downloads#" merged.js
